module.exports = {
	arrowParens: 'always',
	bracketSpacing: true,
	embeddedLanguageFormatting: 'auto',
	htmlWhitespaceSensitivity: 'css',
	insertPragma: false,
	bracketSameLine: false,
	jsxSingleQuote: true,
	proseWrap: 'preserve',
	quoteProps: 'as-needed',
	requirePragma: false,
	semi: true,
	singleQuote: true,
	tabWidth: 2,
	trailingComma: 'es5',
	useTabs: true,
	vueIndentScriptAndStyle: false,
	printWidth: 80,
	eslintIntegration: true,
	stylelintIntegration: true,
	includeLanguages: {
		javascript: 'javascriptreact',
		typescript: 'typescriptreact',
		'jsx-sublime-babel-tags': 'javascriptreact',
		SCSS: 'CSS',
	},
};
